### ISSUE TITLE
Add support for URLs in OpenShift Application Explorer

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/intellij-openshift-connector#45]
We should support displaying and managing URLs in the OpenShift Application explorer.

- [x] Display URLs in the tree (#46)
- [x] multi URLs creation (#50)
- [x] allow to delete an URL (#47)
- [x] open a browser from a URL (#48)
