### ISSUE TITLE
Cover "Project node (logged out)" in UI tests for Jenkins

### ISSUE THREAD

**Issue by martinszuc** [redhat-developer/intellij-openshift-connector#592]
UI test cases for component "Project node (logged out)":

- [x] Default node is shown as kubernetes.svc or similar (when no kubeconfig is present or user is not logged in)
- [x] Can login to a cluster in ~~different ways~~ with username/password
- [x] Paste Login Command works in Cluster login
- [ ] ~~Login via RH Developer Sandbox works~~ (so far not possible to automate)
- [x] Getting Started can be opened
- [x] About shows appropriate information (when logged in and logged out)
