### ISSUE TITLE
Epic: Implement OpenShift Serverless Functions workflow in OpenShift Toolkit for IntelliJ

### ISSUE THREAD

**Issue by sbouchet** [redhat-developer/intellij-openshift-connector#887]
Implement the OpenShift Serverless below features into OpenShift Toolkit extension for IntelliJ.

- [] Add a new node in the navigation with name as `Serverless Functions`
- [] Update to latest `func cli` https://github.com/knative/func
- [] Implement `create` action 
- [] Implement `build` action 
- [] Implement `run` action 
- [] Implement `deploy` action 
- [] Implement `invoke` action

**Comment by adietish** [comment]
According to @mohitsuman's plan we should priotize #924 which is more urgent that this for now
