### ISSUE TITLE
Migrate the odo commands

### ISSUE THREAD

**Issue by adietish** [redhat-developer/intellij-openshift-connector#924]
The extension should figure out a workflow to have NO usage of the odo commands.
This issue is a copy of the same issue in vscode: https://github.com/redhat-developer/vscode-openshift-tools/issues/4320

- [ ] registry / registry --details --devfile (In progress: #4189)                                         
- [ ] preference view / preference add registry / preference remove registry (In progress: #3850) 
- [ ] deploy (In progress: https://github.com/redhat-developer/vscode-openshift-tools/issues/4482)
- [ ] delete component
- [ ] dev (In progress: https://github.com/redhat-developer/vscode-openshift-tools/issues/4541)
- [ ] describe component
- [ ] logs (In progress: https://github.com/redhat-developer/vscode-openshift-tools/issues/4396)
- [ ] init
- [ ] run
- [ ] analyze (#4344)
